#!/usr/bin/env python3
"""Embed the reviewed JS verbatim so standalone helpers need no runtime resource lookup."""
from pathlib import Path
import argparse

root = Path(__file__).resolve().parents[1]
source = root / "integrations/opencode/claudio.js"
target = root / "helper/Sources/ClaudioCore/OpenCodePluginSource.swift"
body = source.read_text()
escaped = body.replace('\\', '\\\\').replace(chr(34), '\\' + chr(34))
rendered = '// Generated by scripts/embed-opencode-plugin.py; edit integrations/opencode/claudio.js.\n'
rendered += 'enum OpenCodePluginSource {\n    static let template = """\n'
rendered += ''.join(('        ' + line) if line.strip() else line for line in escaped.splitlines(keepends=True))
rendered += '        """ + "\\n"\n}\n'
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
if args.check:
    if not target.exists() or target.read_text() != rendered:
        raise SystemExit('OpenCode embedded source differs; run scripts/embed-opencode-plugin.py')
else:
    target.write_text(rendered)
